pipeline {
    agent any
    
    environment {
        PYTHON_PATH = 'C:\\Users\\lukas\\AppData\\Local\\Programs\\Python\\Python311\\python.exe'
        PIP_PATH = 'C:\\Users\\lukas\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\pip.exe'
        CHROME_DRIVER_PATH = 'C:\\WebDriver\\chromedriver.exe'
    }
    
    stages {
        stage('Setup') {
            steps {
                sh 'python -m pip install selenium==4.29.0 requests==2.31.0'
            }
        }
        
        stage('Test') {
            steps {
                sh 'python -m unittest broken_images.py -v'
            }
        }
    }
    
    post {
        always {
            // Clean up any temporary files or processes
            sh 'pkill -f chromedriver || true'
        }
    }
} 