pipeline {
    agent any
    
    environment {
        PYTHON_PATH = 'C:\\Users\\lukas\\AppData\\Local\\Programs\\Python\\Python311\\python.exe'
        PIP_PATH = 'C:\\Users\\lukas\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\pip.exe'
        CHROME_DRIVER_PATH = 'C:\\WebDriver\\chromedriver.exe'
    }
    
    stages {
        stage('Setup') {
            steps {
                script {
                    // Install Python dependencies
                    bat "${PIP_PATH} install selenium==4.29.0 requests==2.31.0"
                }
            }
        }
        
        stage('Run Tests') {
            steps {
                script {
                    // Run the Selenium test
                    bat "${PYTHON_PATH} broken_images.py"
                }
            }
        }
    }
    
    post {
        always {
            // Clean up workspace
            cleanWs()
        }
    }
} 